version: "3.9"
services:
  srtrelay:
    image: "ravenium/srtrelay:latest"
    ports:
      - "1935:1935/udp"
    networks:
        - fragforce
    volumes:
        - $PWD/config.toml:/conf/config.toml
  frag_restream_record:
    image: "ravenium/fragconsole:latest"
    ports:
        - "3000:3000"
    command: -s -serverurl http://srtrelay:8080/streams -streamurl srt://srtrelay:1935 -listen 0.0.0.0:3000
    networks:
        - fragforce
    volumes:
        - $PWD/record:/record
networks:
  fragforce:
